### ISSUE TITLE
Wrong CSS padding on Faculty/Add Assessment

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#69] opened 2017-03-04 01:32 UTC
# AbOut Version
326s17
# Description
On the **Faculty**/*semester*/*offering*/"Add Assessment" screen the CSS ".dispForms form" uses padding "10px". "0px" is more appropriate.
# Related issues

**Comment by LoganSWarner** [comment] 2017-03-25 00:40
Duplicate of isse #50

**Closed by LoganSWarner** 2017-03-25 00:40 UTC
Labels: Add, Anomaly, Assessment, CSS, Duplicate, Faculty, Implementation
